os: linux
language: rust
sudo: false
rust:
  - 1.20.0
  - stable
before_script:
  - pip install -v 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - if [[ -e ~/Library/Python/2.7/bin ]]; then export PATH=~/Library/Python/2.7/bin:$PATH; fi
script:
  - travis-cargo build
notifications:
  email:
    on_success: never
