os: linux
language: rust
sudo: required
env:
  - GTK=3.22
addons:
  apt:
    packages:
      - libgtk-3-dev
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build
notifications:
  email:
    on_success: never
